const AUTH_FAILURE = "AUTH_FAILURE";
const AUTH_SUCCESS = "AUTH_SUCCESS";
const AUTH_REQUEST = "AUTH_REQUEST";
const BASE_AUTH_URL =
  "https://www.googleapis.com/identitytoolkit/v3/relyingparty/";
const API_KEY = "AIzaSyC_6wgsX4LRNGBchK8Gi5dwNexifLI4bFI";
const RESET = "RESET";
const SEND_EMAIL_VERIFICATION_SUCCESS = "SEND_EMAIL_VERIFICATION_SUCCESS";
const VERIFY_EMAIL = "VERIFY_EMAIL";

export {
  AUTH_FAILURE,
  AUTH_SUCCESS,
  AUTH_REQUEST,
  BASE_AUTH_URL,
  API_KEY,
  RESET,
  SEND_EMAIL_VERIFICATION_SUCCESS,
  VERIFY_EMAIL
};
